name: Nightly job

on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0
      with:
        node-version: 12.x
        check-latest: true
    - run: npm install && node src/job.js
